## A code to create a random 3 dimensional array 

In [1]:
ls

3D_DATA.ipynb                     Pinkrah_temperature.nc  Untitled.ipynb
cru_ts4.06.1901.2021.tmp.dat.nc*  TUTORIALS.ipynb         year.nc
cru_ts4.06.2011.2020.pre.dat.nc   TUTORIALS.txt
OUTputfile.nc                     Untitled1.ipynb


In [39]:
import numpy as np
import xarray as xr
import pandas as pd


In [26]:
for x in range(21,42,1):
    print(x+273)



294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314


In [42]:
### 1

In [48]:

# I am defining the shape of the 3D array here with time, latitude, and longitude
shape = (12, 12, 12)  #  The digits here is showing the number of time steps, latitude, longitude points I want create so you can adjust that, 
#SO I want to make it 12 months does why I made it 12,12,12.

# Now I am about to create a random values of temperature with normal temperature and I will convert it to Kelvin
temperature_data = np.random.uniform(20+273, 40+273, size=shape)
temperature_data

array([[[308.32722314, 296.5414156 , 303.00255408, ..., 309.44056584,
         308.12901182, 311.8605988 ],
        [305.20888176, 294.54652669, 300.92558706, ..., 306.03009688,
         299.06003146, 296.46087961],
        [300.36000673, 297.80342874, 294.00892976, ..., 304.83191127,
         298.5282167 , 294.92039402],
        ...,
        [300.56691236, 293.19911161, 307.73081443, ..., 311.80459052,
         307.99012564, 310.19709092],
        [298.03687295, 304.91677393, 302.30880402, ..., 303.40124852,
         293.02449835, 305.88635245],
        [295.24242508, 306.36771729, 311.19539791, ..., 294.91369905,
         295.95085246, 294.93672612]],

       [[301.23532559, 300.57608295, 310.92828059, ..., 301.85060485,
         304.77674286, 308.56149964],
        [306.72276724, 299.52244899, 301.86438944, ..., 311.52774929,
         299.49320672, 303.02340759],
        [309.88571735, 299.67296548, 299.06170467, ..., 304.42441588,
         295.21697501, 309.99191228],
        ...,


In [50]:
# Define the coordinates for each dimension:
# Time: A range of 4 dates starting from '2025-01-01', with a daily frequency
#Now I told Python to range my date from 2025 and assign it to shape 1 of the shape =(4,4,4), check the one I did in Question 1, 
#remember python starts reading from 0 thats why I did periods=shape[0], so meaning the time will take the firstt column. You feel me?
time = pd.date_range('2025-01', periods=shape[0], freq='ME')
time

DatetimeIndex(['2025-01-31', '2025-02-28', '2025-03-31', '2025-04-30',
               '2025-05-31', '2025-06-30', '2025-07-31', '2025-08-31',
               '2025-09-30', '2025-10-31', '2025-11-30', '2025-12-31'],
              dtype='datetime64[ns]', freq='ME')

In [57]:
# FOR THE SECOND COLUMN i WILL represent it by the lat as you said, and it will take shape 1 because python starts reading -
#from 0 and we gave the o column to time and and the 1 is for this lat, so i will generate random values for lat using linspace from -+10
#Latitude: 12 values linearly spaced from -10 to 10 which Ghana is within
lat = np.linspace(-10, 10, shape[1])
lat

array([-10.        ,  -8.18181818,  -6.36363636,  -4.54545455,
        -2.72727273,  -0.90909091,   0.90909091,   2.72727273,
         4.54545455,   6.36363636,   8.18181818,  10.        ])

In [63]:
# This for the Longitudes:  spaced from -10 to 10
lon = np.linspace(-10, 10, shape[2])
lon

array([-10.        ,  -8.18181818,  -6.36363636,  -4.54545455,
        -2.72727273,  -0.90909091,   0.90909091,   2.72727273,
         4.54545455,   6.36363636,   8.18181818,  10.        ])

In [64]:
## 3

In [65]:
# specify the coordinates example the lat we did should show as lat, 
#so as lon and time, just as the ones we see in normal data, you see to select time in data to work with we do sel(time='2020'), 
#now we want to make this data as such to show the time, lat, lon so someone can cll those variables to work with.

#naming the dimension or column for time as time
time_coord = xr.DataArray(time, dims=["time"], name="time")

# specifying the dimension name lat as "lat"
lat_coord = xr.DataArray(lat, dims=["lat"], name="lat")

# this is for lon
lon_coord = xr.DataArray(lon, dims=["lon"], name="lon")

In [71]:

# now I will be linking everything together, so we performed those task separately
# The temperature data is linked to time, latitude, and longitude through the `coords` argument

my_temperature = xr.DataArray(temperature_data,coords=[time_coord, lat_coord, lon_coord], dims=["time", "lat", "lon"], name="temperature")
my_temperature


<xarray.DataArray 'temperature' (time: 12, lat: 12, lon: 12)> Size: 14kB
array([[[308.32722314, 296.5414156 , 303.00255408, ..., 309.44056584,
         308.12901182, 311.8605988 ],
        [305.20888176, 294.54652669, 300.92558706, ..., 306.03009688,
         299.06003146, 296.46087961],
        [300.36000673, 297.80342874, 294.00892976, ..., 304.83191127,
         298.5282167 , 294.92039402],
        ...,
        [300.56691236, 293.19911161, 307.73081443, ..., 311.80459052,
         307.99012564, 310.19709092],
        [298.03687295, 304.91677393, 302.30880402, ..., 303.40124852,
         293.02449835, 305.88635245],
        [295.24242508, 306.36771729, 311.19539791, ..., 294.91369905,
         295.95085246, 294.93672612]],

       [[301.23532559, 300.57608295, 310.92828059, ..., 301.85060485,
         304.77674286, 308.56149964],
        [306.72276724, 299.52244899, 301.86438944, ..., 311.52774929,
         299.49320672, 303.02340759],
        [309.88571735, 299.67296548, 299.06170467, ..., 304.42441588,
         295.21697501, 309.99191228],
...
        [303.1804582 , 304.43062819, 307.51699309, ..., 299.2345392 ,
         300.25258867, 295.02624332],
        [307.18049866, 303.47237666, 304.90518445, ..., 301.28331167,
         293.92220247, 296.10813727],
        [301.93747921, 309.83114833, 306.8621687 , ..., 302.83424709,
         302.2480804 , 298.04977148]],

       [[310.58855479, 305.61379046, 293.4012326 , ..., 311.73069774,
         305.49749112, 306.55839133],
        [296.68764572, 300.36115767, 309.09861066, ..., 312.65332421,
         295.02096369, 308.33300335],
        [300.76132896, 312.04543607, 305.90320849, ..., 303.94670057,
         293.95428927, 299.54330938],
        ...,
        [293.76896711, 310.64594482, 311.62346355, ..., 301.54991624,
         308.08075969, 296.9854443 ],
        [296.44647994, 312.37454948, 293.15640411, ..., 309.60917759,
         302.53859479, 301.07921413],
        [307.19273588, 295.28013669, 295.98911096, ..., 293.25736654,
         302.68802116, 302.52629771]]])
Coordinates:
  * time     (time) datetime64[ns] 96B 2025-01-31 2025-02-28 ... 2025-12-31
  * lat      (lat) float64 96B -10.0 -8.182 -6.364 -4.545 ... 6.364 8.182 10.0
  * lon      (lon) float64 96B -10.0 -8.182 -6.364 -4.545 ... 6.364 8.182 10.0